{ ... }:
{
	wayland.windowManager.hyprland.settings = {
		"$mod" = "SUPER"; 
		"$terminal" = "kitty"; # Or your preferred terminal
		"$fileManager" = "thunar"; # Or your preferred file manager
		"$menu" = "wofi --show drun"; # Or your preferred menu
		"$browser" = "zen";

		bind = [
			"$mod,Return,exec,$terminal"
			"$modSHIFT,Return,exec,rofi-launcher"
			"$modSHIFT,W,exec,web-search"
			"$modALT,W,exec,wallsetter"
			"$modSHIFT,N,exec,swaync-client -rs"
			"$mod,W,exec,$browser"
			"$mod,E,exec,emopicker9000"
			"$mod,S,exec,screenshootin"
			"$mod,D,exec,discord"
			"$mod,O,exec,obs"
			"$mod,C,exec,hyprpicker -a"
			"$mod,G,exec,gimp"
			"$modSHIFT,G,exec,godot4"
			"$mod,T,exec,thunar"
			"$mod,M,exec,spotify"
			"$mod,Q,killactive"
			"$mod,P,pseudo"
			"$modSHIFT,I,togglesplit"
			"$mod,F,fullscreen"
			"$modSHIFT,F,togglefloating"
			"$modSHIFT,C,exit"
			"$modSHIFT,left,movewindow,l"
			"$modSHIFT,right,movewindow,r"
			"$modSHIFT,up,movewindow,u"
			"$modSHIFT,down,movewindow,d"
			"$modSHIFT,h,movewindow,l"
			"$modSHIFT,l,movewindow,r"
			"$modSHIFT,k,movewindow,u"
			"$modSHIFT,j,movewindow,d"
			"$mod,left,movefocus,l"
			"$mod,right,movefocus,r"
			"$mod,up,movefocus,u"
			"$mod,down,movefocus,d"
			"$mod,h,movefocus,l"
			"$mod,l,movefocus,r"
			"$mod,k,movefocus,u"
			"$mod,j,movefocus,d"
			"$mod,1,workspace,1"
			"$mod,2,workspace,2"
			"$mod,3,workspace,3"
			"$mod,4,workspace,4"
			"$mod,5,workspace,5"
			"$mod,6,workspace,6"
			"$mod,7,workspace,7"
			"$mod,8,workspace,8"
			"$mod,9,workspace,9"
			"$mod,0,workspace,10"
			"$modSHIFT,SPACE,movetoworkspace,special"
			"$mod,SPACE,togglespecialworkspace"
			"$modSHIFT,1,movetoworkspace,1"
			"$modSHIFT,2,movetoworkspace,2"
			"$modSHIFT,3,movetoworkspace,3"
			"$modSHIFT,4,movetoworkspace,4"
			"$modSHIFT,5,movetoworkspace,5"
			"$modSHIFT,6,movetoworkspace,6"
			"$modSHIFT,7,movetoworkspace,7"
			"$modSHIFT,8,movetoworkspace,8"
			"$modSHIFT,9,movetoworkspace,9"
			"$modSHIFT,0,movetoworkspace,10"
			"$modCONTROL,right,workspace,e+1"
			"$modCONTROL,left,workspace,e-1"
			"$mod,mouse_down,workspace, e+1"
			"$mod,mouse_up,workspace, e-1"
			"$mod,mouse:272,movewindow"
			#"$mod,mouse:273,resizewindow"
			"ALT,Tab,cyclenext" 
			"ALT,Tab,bringactivetotop" 
			",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
			",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
			",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle" # binde is not needed
			",XF86AudioPlay, exec, playerctl play-pause"
			",XF86AudioPause, exec, playerctl play-pause"
			",XF86AudioNext, exec, playerctl next"
			",XF86AudioPrev, exec, playerctl previous"
			",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
			",XF86MonBrightnessUp,exec,brightnessctl set +5%"
		];
    };
}
